"""Comprehensive list of Greater Sydney suburbs for text matching.

Source: Wikipedia — List of Sydney suburbs (ABS Suburb and Locality boundaries).
Covers all ~660 officially designated suburbs in Greater Sydney.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Canonical suburb names (title case, alphabetical)
# ---------------------------------------------------------------------------
ALL_SUBURBS: tuple[str, ...] = (
    "Abbotsbury",
    "Abbotsford",
    "Acacia Gardens",
    "Agnes Banks",
    "Airds",
    "Alexandria",
    "Alfords Point",
    "Allambie Heights",
    "Allawah",
    "Ambarvale",
    "Annandale",
    "Annangrove",
    "Arcadia",
    "Arncliffe",
    "Arndell Park",
    "Artarmon",
    "Ashbury",
    "Ashcroft",
    "Ashfield",
    "Asquith",
    "Auburn",
    "Austral",
    "Avalon Beach",
    "Badgerys Creek",
    "Balgowlah",
    "Balgowlah Heights",
    "Balmain",
    "Balmain East",
    "Bangor",
    "Banksia",
    "Banksmeadow",
    "Bankstown",
    "Barangaroo",
    "Barden Ridge",
    "Bardia",
    "Bardwell Park",
    "Bardwell Valley",
    "Bass Hill",
    "Baulkham Hills",
    "Bayview",
    "Beacon Hill",
    "Beaconsfield",
    "Beaumont Hills",
    "Beecroft",
    "Belfield",
    "Bella Vista",
    "Bellevue Hill",
    "Belmore",
    "Belrose",
    "Berala",
    "Berkshire Park",
    "Berowra",
    "Berowra Heights",
    "Berowra Waters",
    "Berrilee",
    "Beverley Park",
    "Beverly Hills",
    "Bexley",
    "Bexley North",
    "Bidwill",
    "Bilgola Beach",
    "Bilgola Plateau",
    "Birchgrove",
    "Birrong",
    "Blackett",
    "Blacktown",
    "Blakehurst",
    "Bligh Park",
    "Bondi",
    "Bondi Beach",
    "Bondi Junction",
    "Bonnet Bay",
    "Bonnyrigg",
    "Bonnyrigg Heights",
    "Bossley Park",
    "Botany",
    "Box Hill",
    "Bradbury",
    "Breakfast Point",
    "Brighton-Le-Sands",
    "Bringelly",
    "Bronte",
    "Brooklyn",
    "Brookvale",
    "Bundeena",
    "Bungarribee",
    "Burraneer",
    "Burwood",
    "Burwood Heights",
    "Busby",
    "Cabarita",
    "Cabramatta",
    "Cabramatta West",
    "Caddens",
    "Cambridge Gardens",
    "Cambridge Park",
    "Camden",
    "Camden South",
    "Camellia",
    "Cammeray",
    "Campbelltown",
    "Camperdown",
    "Campsie",
    "Canada Bay",
    "Canley Heights",
    "Canley Vale",
    "Canoelands",
    "Canterbury",
    "Caringbah",
    "Caringbah South",
    "Carlingford",
    "Carlton",
    "Carnes Hill",
    "Carramar",
    "Carss Park",
    "Cartwright",
    "Castle Cove",
    "Castle Hill",
    "Castlecrag",
    "Castlereagh",
    "Casula",
    "Catherine Field",
    "Cattai",
    "Cecil Hills",
    "Cecil Park",
    "Centennial Park",
    "Chatswood",
    "Chatswood West",
    "Cheltenham",
    "Cherrybrook",
    "Chester Hill",
    "Chippendale",
    "Chipping Norton",
    "Chiswick",
    "Chullora",
    "Church Point",
    "Claremont Meadows",
    "Clarendon",
    "Clareville",
    "Claymore",
    "Clemton Park",
    "Clontarf",
    "Clovelly",
    "Clyde",
    "Cobbitty",
    "Colebee",
    "Collaroy",
    "Collaroy Plateau",
    "Colyton",
    "Como",
    "Concord",
    "Concord West",
    "Condell Park",
    "Connells Point",
    "Constitution Hill",
    "Coogee",
    "Cornwallis",
    "Cottage Point",
    "Cowan",
    "Cranebrook",
    "Cremorne",
    "Cremorne Point",
    "Cromer",
    "Cronulla",
    "Crows Nest",
    "Croydon",
    "Croydon Park",
    "Curl Curl",
    "Currans Hill",
    "Daceyville",
    "Dangar Island",
    "Darling Point",
    "Darlinghurst",
    "Darlington",
    "Davidson",
    "Dawes Point",
    "Dean Park",
    "Dee Why",
    "Denham Court",
    "Denistone",
    "Denistone East",
    "Denistone West",
    "Dharruk",
    "Dolans Bay",
    "Dolls Point",
    "Doonside",
    "Double Bay",
    "Dover Heights",
    "Drummoyne",
    "Duffys Forest",
    "Dulwich Hill",
    "Dundas",
    "Dundas Valley",
    "Dural",
    "Eagle Vale",
    "Earlwood",
    "East Gordon",
    "East Hills",
    "East Killara",
    "East Lindfield",
    "East Ryde",
    "Eastern Creek",
    "Eastgardens",
    "Eastlakes",
    "Eastwood",
    "Edensor Park",
    "Edgecliff",
    "Edmondson Park",
    "Elanora Heights",
    "Elderslie",
    "Elizabeth Bay",
    "Elizabeth Hills",
    "Emerton",
    "Emu Heights",
    "Emu Plains",
    "Enfield",
    "Engadine",
    "Enmore",
    "Epping",
    "Ermington",
    "Erskine Park",
    "Erskineville",
    "Eschol Park",
    "Eveleigh",
    "Fairfield",
    "Fairfield East",
    "Fairfield Heights",
    "Fairfield West",
    "Fairlight",
    "Five Dock",
    "Flemington",
    "Forest Lodge",
    "Forestville",
    "Freemans Reach",
    "Frenchs Forest",
    "Freshwater",
    "Galston",
    "Georges Hall",
    "Girraween",
    "Gladesville",
    "Glebe",
    "Gledswood Hills",
    "Glen Alpine",
    "Glendenning",
    "Glenfield",
    "Glenhaven",
    "Glenmore Park",
    "Glenorie",
    "Glenwood",
    "Glossodia",
    "Gordon",
    "Granville",
    "Grays Point",
    "Great Mackerel Beach",
    "Green Valley",
    "Greenacre",
    "Greendale",
    "Greenfield Park",
    "Greenhills Beach",
    "Greenwich",
    "Gregory Hills",
    "Greystanes",
    "Grose Vale",
    "Grose Wold",
    "Guildford",
    "Guildford West",
    "Gymea",
    "Gymea Bay",
    "Haberfield",
    "Hammondville",
    "Harrington Park",
    "Harris Park",
    "Hassall Grove",
    "Haymarket",
    "Heathcote",
    "Hebersham",
    "Heckenberg",
    "Hillsdale",
    "Hinchinbrook",
    "Hobartville",
    "Holroyd",
    "Holsworthy",
    "Homebush",
    "Homebush West",
    "Horningsea Park",
    "Hornsby",
    "Hornsby Heights",
    "Horsley Park",
    "Hoxton Park",
    "Hunters Hill",
    "Huntingwood",
    "Huntleys Cove",
    "Huntleys Point",
    "Hurlstone Park",
    "Hurstville",
    "Hurstville Grove",
    "Illawong",
    "Ingleburn",
    "Ingleside",
    "Jamisontown",
    "Jannali",
    "Jordan Springs",
    "Kangaroo Point",
    "Kareela",
    "Kearns",
    "Kellyville",
    "Kellyville Ridge",
    "Kemps Creek",
    "Kensington",
    "Kenthurst",
    "Kentlyn",
    "Killara",
    "Killarney Heights",
    "Kings Langley",
    "Kings Park",
    "Kingsford",
    "Kingsgrove",
    "Kingswood",
    "Kingswood Park",
    "Kirkham",
    "Kirrawee",
    "Kirribilli",
    "Kogarah",
    "Kogarah Bay",
    "Ku-ring-gai Chase",
    "Kurmond",
    "Kurnell",
    "Kurraba Point",
    "Kurrajong",
    "Kurrajong Hills",
    "Kyeemagh",
    "Kyle Bay",
    "La Perouse",
    "Lakemba",
    "Lalor Park",
    "Lane Cove",
    "Lane Cove North",
    "Lane Cove West",
    "Lansdowne",
    "Lansvale",
    "Lavender Bay",
    "Leets Vale",
    "Leichhardt",
    "Leonay",
    "Leppington",
    "Lethbridge Park",
    "Leumeah",
    "Lewisham",
    "Liberty Grove",
    "Lidcombe",
    "Lilli Pilli",
    "Lilyfield",
    "Lindfield",
    "Linley Point",
    "Little Bay",
    "Liverpool",
    "Llandilo",
    "Loftus",
    "Londonderry",
    "Longueville",
    "Lovett Bay",
    "Lower Portland",
    "Lucas Heights",
    "Luddenham",
    "Lugarno",
    "Lurnea",
    "Macquarie Fields",
    "Macquarie Links",
    "Macquarie Park",
    "Maianbar",
    "Malabar",
    "Manly",
    "Manly Vale",
    "Maraylya",
    "Marayong",
    "Maroota",
    "Maroubra",
    "Marrickville",
    "Marsden Park",
    "Marsfield",
    "Mascot",
    "Matraville",
    "Mays Hill",
    "McGraths Hill",
    "McMahons Point",
    "Meadowbank",
    "Melrose Park",
    "Menai",
    "Menangle Park",
    "Merrylands",
    "Merrylands West",
    "Middle Cove",
    "Middle Dural",
    "Middleton Grange",
    "Miller",
    "Millers Point",
    "Milperra",
    "Milsons Point",
    "Minchinbury",
    "Minto",
    "Minto Heights",
    "Miranda",
    "Mona Vale",
    "Monterey",
    "Moore Park",
    "Moorebank",
    "Mortdale",
    "Mortlake",
    "Mosman",
    "Mount Annan",
    "Mount Colah",
    "Mount Druitt",
    "Mount Kuring-Gai",
    "Mount Lewis",
    "Mount Pritchard",
    "Mount Vernon",
    "Mulgoa",
    "Narellan",
    "Narellan Vale",
    "Naremburn",
    "Narrabeen",
    "Narraweena",
    "Narwee",
    "Neutral Bay",
    "Newington",
    "Newport",
    "Newtown",
    "Normanhurst",
    "North Balgowlah",
    "North Bondi",
    "North Curl Curl",
    "North Epping",
    "North Kellyville",
    "North Manly",
    "North Narrabeen",
    "North Parramatta",
    "North Richmond",
    "North Rocks",
    "North Ryde",
    "North St Ives",
    "North St Marys",
    "North Strathfield",
    "North Sydney",
    "North Turramurra",
    "North Wahroonga",
    "North Willoughby",
    "Northbridge",
    "Northmead",
    "Northwood",
    "Norwest",
    "Oakhurst",
    "Oakville",
    "Oatlands",
    "Oatley",
    "Old Guildford",
    "Old Toongabbie",
    "Oran Park",
    "Orchard Hills",
    "Oxford Falls",
    "Oyster Bay",
    "Paddington",
    "Padstow",
    "Padstow Heights",
    "Pagewood",
    "Palm Beach",
    "Panania",
    "Parklea",
    "Parramatta",
    "Peakhurst",
    "Peakhurst Heights",
    "Pemulwuy",
    "Pendle Hill",
    "Pennant Hills",
    "Penrith",
    "Penshurst",
    "Petersham",
    "Picnic Point",
    "Pitt Town",
    "Pleasure Point",
    "Plumpton",
    "Point Piper",
    "Potts Hill",
    "Potts Point",
    "Prairiewood",
    "Prestons",
    "Prospect",
    "Punchbowl",
    "Putney",
    "Pymble",
    "Pyrmont",
    "Quakers Hill",
    "Queens Park",
    "Queenscliff",
    "Raby",
    "Ramsgate",
    "Ramsgate Beach",
    "Randwick",
    "Redfern",
    "Regents Park",
    "Regentville",
    "Revesby",
    "Revesby Heights",
    "Rhodes",
    "Richmond",
    "Riverstone",
    "Riverview",
    "Riverwood",
    "Rockdale",
    "Rodd Point",
    "Rookwood",
    "Rooty Hill",
    "Ropes Crossing",
    "Rose Bay",
    "Rosebery",
    "Rosehill",
    "Roselands",
    "Rosemeadow",
    "Roseville",
    "Roseville Chase",
    "Rossmore",
    "Rouse Hill",
    "Rozelle",
    "Rushcutters Bay",
    "Russell Lea",
    "Rydalmere",
    "Ryde",
    "Sackville",
    "Sadleir",
    "Sandringham",
    "Sans Souci",
    "Scheyville",
    "Schofields",
    "Scotland Island",
    "Seaforth",
    "Sefton",
    "Seven Hills",
    "Shalvey",
    "Silverwater",
    "Smeaton Grange",
    "Smithfield",
    "South Coogee",
    "South Granville",
    "South Hurstville",
    "South Penrith",
    "South Turramurra",
    "South Wentworthville",
    "South Windsor",
    "Spring Farm",
    "St Andrews",
    "St Clair",
    "St Helens Park",
    "St Ives",
    "St Ives Chase",
    "St Johns Park",
    "St Leonards",
    "St Marys",
    "St Peters",
    "Stanhope Gardens",
    "Stanmore",
    "Strathfield",
    "Strathfield South",
    "Summer Hill",
    "Surry Hills",
    "Sutherland",
    "Sydenham",
    "Sydney Olympic Park",
    "Sylvania",
    "Sylvania Waters",
    "Tallawong",
    "Tamarama",
    "Taren Point",
    "Telopea",
    "Tempe",
    "Tennyson Point",
    "Terrey Hills",
    "The Ponds",
    "The Rocks",
    "Thornleigh",
    "Toongabbie",
    "Tregear",
    "Turramurra",
    "Turrella",
    "Ultimo",
    "Vaucluse",
    "Villawood",
    "Vineyard",
    "Voyager Point",
    "Wahroonga",
    "Waitara",
    "Wakeley",
    "Wallacia",
    "Wareemba",
    "Warrawee",
    "Warriewood",
    "Warwick Farm",
    "Waterfall",
    "Waterloo",
    "Watsons Bay",
    "Wattle Grove",
    "Waverley",
    "Waverton",
    "Wedderburn",
    "Wentworth Point",
    "Wentworthville",
    "Werrington",
    "Werrington Downs",
    "West Hoxton",
    "West Killara",
    "West Pennant Hills",
    "West Pymble",
    "West Ryde",
    "Westleigh",
    "Westmead",
    "Wetherill Park",
    "Whalan",
    "Whale Beach",
    "Wheeler Heights",
    "Wilberforce",
    "Wiley Park",
    "Willmot",
    "Willoughby",
    "Willoughby East",
    "Windsor",
    "Windsor Downs",
    "Winston Hills",
    "Wisemans Ferry",
    "Wolli Creek",
    "Wollstonecraft",
    "Woodbine",
    "Woodcroft",
    "Woollahra",
    "Woolloomooloo",
    "Woolooware",
    "Woolwich",
    "Woronora",
    "Woronora Heights",
    "Yagoona",
    "Yarrawarrah",
    "Yennora",
    "Yowie Bay",
    "Zetland",
)

# ---------------------------------------------------------------------------
# Ambiguous suburb names — common English words, personal names, or names of
# well-known non-Sydney places.  These require geographic context words nearby
# to be counted as suburb mentions.
# ---------------------------------------------------------------------------
AMBIGUOUS_SUBURBS: frozenset[str] = frozenset({
    "Auburn",           # hair colour / personal name
    "Banksia",          # plant genus
    "Beverly Hills",    # famous US city
    "Brooklyn",         # famous US borough
    "Camden",           # UK place / name
    "Canterbury",       # UK city
    "Carlton",          # personal name
    "Clyde",            # personal name
    "Como",             # Italian city
    "Concord",          # US city / concept
    "Croydon",          # UK city
    "Davidson",         # personal name
    "Enfield",          # UK place
    "Fairfield",        # generic place name
    "Gordon",           # personal name
    "Kensington",       # famous London area
    "Liverpool",        # major UK city
    "Miller",           # occupation / personal name
    "Miranda",          # personal name
    "Nelson",           # personal name
    "Newport",          # multiple places worldwide
    "Paddington",       # London area
    "Prospect",         # common English word
    "Putney",           # London area
    "Rhodes",           # Greek island / personal name
    "Richmond",         # multiple places worldwide
    "Sandringham",      # UK royal estate
    "Smithfield",       # generic / UK market
    "Vineyard",         # common English word
    "Waterfall",        # common English word
    "Waterloo",         # famous battle / London station
    "Windsor",          # UK castle / city
})

# Context words that indicate geographic usage (suburb being discussed as a place).
GEOGRAPHIC_CONTEXT_WORDS: tuple[str, ...] = (
    "suburb", "area", "live in", "living in", "moved to", "moving to",
    "move to", "near", "around", "station", "commute", "rent in",
    "renting in", "apartment", "flat", "house in", "unit in",
    "neighbourhood", "neighborhood", "council", "lga",
)

# Window size (chars) to search for context around an ambiguous match.
CONTEXT_WINDOW = 80


# ---------------------------------------------------------------------------
# Suburb matcher — builds a compiled regex for fast text scanning
# ---------------------------------------------------------------------------

def build_suburb_matcher() -> tuple[re.Pattern, dict[str, str]]:
    """Build a compiled regex that matches any Sydney suburb name.

    Returns:
        pattern: Compiled regex with word boundaries.
        match_to_canonical: Mapping from lowercase match string to canonical
            suburb name (title case).
    """
    match_to_canonical: dict[str, str] = {}
    patterns: list[str] = []

    for suburb in ALL_SUBURBS:
        lower = suburb.lower()
        escaped = re.escape(lower)
        patterns.append(escaped)
        match_to_canonical[lower] = suburb

    # Sort longest-first so "Surry Hills" matches before "Hills"
    patterns.sort(key=len, reverse=True)

    combined = r"\b(" + "|".join(patterns) + r")\b"
    return re.compile(combined, re.IGNORECASE), match_to_canonical


def _has_geographic_context(text: str, match_start: int, match_end: int) -> bool:
    """Check if an ambiguous suburb match has nearby geographic context words."""
    window_start = max(0, match_start - CONTEXT_WINDOW)
    window_end = min(len(text), match_end + CONTEXT_WINDOW)
    window = text[window_start:window_end].lower()

    return any(ctx in window for ctx in GEOGRAPHIC_CONTEXT_WORDS)


def detect_suburbs(
    text: str,
    pattern: re.Pattern,
    match_to_canonical: dict[str, str],
) -> list[str]:
    """Detect suburb mentions in a text string.

    Args:
        text: Text to scan (post title+body or comment body).
        pattern: Compiled regex from build_suburb_matcher().
        match_to_canonical: Mapping from build_suburb_matcher().

    Returns:
        Deduplicated list of canonical suburb names found in the text.
    """
    found: dict[str, None] = {}  # ordered set via dict

    for match in pattern.finditer(text):
        matched_text = match.group(0).lower()
        canonical = match_to_canonical.get(matched_text)
        if canonical is None:
            continue

        # Skip ambiguous names without geographic context
        if canonical in AMBIGUOUS_SUBURBS:
            if not _has_geographic_context(text, match.start(), match.end()):
                continue

        found[canonical] = None

    return list(found.keys())
